name: Check for compilation failures

on: [push, pull_request]

jobs:
  build:
    name: Check for compilation failures
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install git build-essential autoconf automake nasm curl mtools clang llvm -y

      - name: Build the bootloader (GNU)
        run: ./autogen.sh --enable-werror && make all && make maintainer-clean

      - name: Build the bootloader (LLVM)
        run: ./autogen.sh TOOLCHAIN=llvm --enable-werror && make all && make maintainer-clean
